name: Release Test
on:
  workflow_dispatch:
    inputs:
      supervisor_version:
        description: "Supervisor Version"
        required: true
        default: "latest"
jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add WiX Toolset to PATH
        shell: bash
        run: echo "${WIX}bin" >> $GITHUB_PATH
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: "v2.8.2"
          args: release -f .goreleaser-windows.yaml --parallelism 4 --skip=publish --skip=validate --skip=sign --clean --snapshot --verbose
        env:
          SUPERVISOR_VERSION: ${{ inputs.supervisor_version }}
          GITHUB_TOKEN: ${{ secrets.ORG_GORELEASER_GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - name: Flatten MSI artifacts
        shell: bash
        run: cp dist/msi/**/*.msi dist/
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            dist/*.zip
            dist/*.msi

  release-test:
    needs: release-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-artifacts
          path: windows-artifacts/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: "v2.8.2"
          args: release --parallelism 4 --skip=publish --skip=validate --skip=sign --clean --snapshot --verbose
        env:
          SUPERVISOR_VERSION: ${{ inputs.supervisor_version }}
          GITHUB_TOKEN: ${{ secrets.ORG_GORELEASER_GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - name: Create artifact archive
        run: |
          mkdir artifacts
          cp ./install_scripts/*.sh ./artifacts
          cp ./install_scripts/*.ps1 ./artifacts
          cp ./dist/*.tar.gz ./artifacts
          cp ./dist/*.rpm ./artifacts
          cp ./dist/*.deb ./artifacts
          cp ./dist/*SHA256SUMS ./artifacts
          cp ./windows-artifacts/*.zip ./artifacts
          cp ./windows-artifacts/*.msi ./artifacts
          tar -czvf bindplane-supervisor-${{ github.event.inputs.version }}-artifacts.tar.gz -C ./artifacts .
      - name: Check Artifacts Directory
        run: |
          ls -la artifacts
          du -sh artifacts
      - name: Upload build artifacts
        uses: namespace-actions/upload-artifact@v1
        with:
          name: bindplane-supervisor-${{ github.event.inputs.version }}-artifacts.tar.gz
          path: bindplane-supervisor-${{ github.event.inputs.version }}-artifacts.tar.gz
          retention-days: 1
