name: Release Test
on:
  workflow_dispatch:
    inputs:
      supervisor_version:
        description: "Supervisor Version"
        required: true
        default: "latest"
jobs:
  release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install msitools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build valac libglib2.0-dev libgcab-dev libgsf-1-dev libxml2-dev gobject-introspection libgirepository1.0-dev bison perl
          pip3 install meson
          curl -L -o msitools-0.106.tar.xz https://download.gnome.org/sources/msitools/0.106/msitools-0.106.tar.xz
          tar xf msitools-0.106.tar.xz
          cd msitools-0.106
          meson setup build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: "v2.8.2"
          args: release --parallelism 4 --skip=publish --skip=validate --skip=sign --clean --snapshot --verbose
        env:
          SUPERVISOR_VERSION: ${{ inputs.supervisor_version }}
          GITHUB_TOKEN: ${{ secrets.ORG_GORELEASER_GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
